## 이 사이에서 무슨 일을 하는가? (tf.nn.softmax() ~ tf.nn.softmax_cross_entropy_with_logits())
http://stackoverflow.com/questions/34240703/difference-between-tensorflow-tf-nn-softmax-and-tf-nn-softmax-cross-entropy-with

In [1]:
import tensorflow as tf
print(tf.__version__)
import numpy as np

sess = tf.Session()

# Create example y_hat.
y_hat = tf.convert_to_tensor(np.array([[0.5, 1.5, 0.1],[2.2, 1.3, 1.7]]))
sess.run(y_hat)

1.0.1


array([[ 0.5,  1.5,  0.1],
       [ 2.2,  1.3,  1.7]])

In [2]:
y_true = tf.convert_to_tensor(np.array([[0.0, 1.0, 0.0],[0.0, 0.0, 1.0]]))
sess.run(y_true)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### tf.nn.softmax

In [3]:
y_hat_softmax = tf.nn.softmax(y_hat)
_y_hat_softmax = sess.run(y_hat_softmax)
_y_hat_softmax

array([[ 0.227863  ,  0.61939586,  0.15274114],
       [ 0.49674623,  0.20196195,  0.30129182]])

In [4]:
loss_per_instance_1 = -tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1])
sess.run(loss_per_instance_1)

array([ 0.4790107 ,  1.19967598])

In [5]:
# label값인 y_true의 값이 1인 경우만 의미가 있어, 2개만 처리됨
print(-np.log(_y_hat_softmax[0][1]), -np.log(_y_hat_softmax[1][2]))

0.479010696748 1.19967598121


In [6]:
total_loss_1 = tf.reduce_mean(-tf.reduce_sum(y_true * tf.log(y_hat_softmax), reduction_indices=[1]))
sess.run(total_loss_1)

0.83934333897877944

### tf.nn.softmax_cross_entropy_with_logits

In [7]:
loss_per_instance_2 = tf.nn.softmax_cross_entropy_with_logits(logits=y_hat, labels=y_true)
sess.run(loss_per_instance_2)

array([ 0.4790107 ,  1.19967598])

In [8]:
total_loss_2 = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y_hat, labels=y_true))
sess.run(total_loss_2)

0.83934333897877922

In [9]:
# 0.83934333897877944
# 0.83934333897877922
# 무시할 정도로 작은 부분이 발생하는 것은 왜일까요?