In [4]:
import numpy as np

In [6]:
data_source_row = 366
data_source_column = 6

In [9]:
data_source = np.zeros((data_source_row, data_source_column), dtype=np.float32)

In [10]:
print(data_source)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [17]:
for row in range(data_source_row):
    for column in range(data_source_column):
        data_source[row, column] = row + column / 10
        print("%3.1f" % data_source[row, column])

0.0
0.1
0.2
0.3
0.4
0.5
1.0
1.1
1.2
1.3
1.4
1.5
2.0
2.1
2.2
2.3
2.4
2.5
3.0
3.1
3.2
3.3
3.4
3.5
4.0
4.1
4.2
4.3
4.4
4.5
5.0
5.1
5.2
5.3
5.4
5.5
6.0
6.1
6.2
6.3
6.4
6.5
7.0
7.1
7.2
7.3
7.4
7.5
8.0
8.1
8.2
8.3
8.4
8.5
9.0
9.1
9.2
9.3
9.4
9.5
10.0
10.1
10.2
10.3
10.4
10.5
11.0
11.1
11.2
11.3
11.4
11.5
12.0
12.1
12.2
12.3
12.4
12.5
13.0
13.1
13.2
13.3
13.4
13.5
14.0
14.1
14.2
14.3
14.4
14.5
15.0
15.1
15.2
15.3
15.4
15.5
16.0
16.1
16.2
16.3
16.4
16.5
17.0
17.1
17.2
17.3
17.4
17.5
18.0
18.1
18.2
18.3
18.4
18.5
19.0
19.1
19.2
19.3
19.4
19.5
20.0
20.1
20.2
20.3
20.4
20.5
21.0
21.1
21.2
21.3
21.4
21.5
22.0
22.1
22.2
22.3
22.4
22.5
23.0
23.1
23.2
23.3
23.4
23.5
24.0
24.1
24.2
24.3
24.4
24.5
25.0
25.1
25.2
25.3
25.4
25.5
26.0
26.1
26.2
26.3
26.4
26.5
27.0
27.1
27.2
27.3
27.4
27.5
28.0
28.1
28.2
28.3
28.4
28.5
29.0
29.1
29.2
29.3
29.4
29.5
30.0
30.1
30.2
30.3
30.4
30.5
31.0
31.1
31.2
31.3
31.4
31.5
32.0
32.1
32.2
32.3
32.4
32.5
33.0
33.1
33.2
33.3
33.4
33.5
34.0
34.1
34.2
34.3
34.4
34.5
35.0
35.1


In [23]:
num_of_data = 60
start_row = 0
for row in range(data_source_row - num_of_data):
    for column in range(data_source_column):
        print("start_row : ", start_row, "    sum : ", np.sum(data_source[start_row:start_row+num_of_data, column]))
        
    start_row = start_row + 1

start_row :  0     sum :  1770.0
start_row :  0     sum :  1776.0
start_row :  0     sum :  1782.0
start_row :  0     sum :  1788.0
start_row :  0     sum :  1794.0
start_row :  0     sum :  1800.0
start_row :  1     sum :  1830.0
start_row :  1     sum :  1836.0
start_row :  1     sum :  1842.0
start_row :  1     sum :  1848.0
start_row :  1     sum :  1854.0
start_row :  1     sum :  1860.0
start_row :  2     sum :  1890.0
start_row :  2     sum :  1896.0
start_row :  2     sum :  1902.0
start_row :  2     sum :  1908.0
start_row :  2     sum :  1914.0
start_row :  2     sum :  1920.0
start_row :  3     sum :  1950.0
start_row :  3     sum :  1956.0
start_row :  3     sum :  1962.0
start_row :  3     sum :  1968.0
start_row :  3     sum :  1974.0
start_row :  3     sum :  1980.0
start_row :  4     sum :  2010.0
start_row :  4     sum :  2016.0
start_row :  4     sum :  2022.0
start_row :  4     sum :  2028.0
start_row :  4     sum :  2034.0
start_row :  4     sum :  2040.0
start_row 